app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('user/', include('users.urls', namespace='users')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('delete_task/', views.TaskDeleteView.as_view(), name='delete_task'),
    path('update_task/', views.TaskUpdateView.as_view(), name='update_task'),
    # path('add_task/', views.create_task, name='add_task'),
]

tasks/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
from users.models import TaskUser

class Task(models.Model):
    user = models.ForeignKey(to=TaskUser, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Категория")
    text = models.TextField(verbose_name="Текст задачи")
    date = models.DateField(default=timezone.now, verbose_name="Дата задачи")
    is_done = models.BooleanField(default=False, verbose_name="Выполнено")
    session_key = models.CharField(max_length=32, null=True, blank=True)

    class Meta:
        db_table = 'task'
        verbose_name = "задача"
        verbose_name_plural = "Задачи"
        ordering = ("id", )

    def __str__(self):
        return f"{self.user.username if self.user else 'null'}: {self.text[:10]} | {self.date} | {self.is_done}"

tasks/forms.py
from django import forms

from tasks.models import Task

class TaskCreateForm(forms.ModelForm):
    text = forms.CharField()
    date = forms.DateField(required=True)
    session_key = forms.CharField(required=False, max_length=32)
    user_id = forms.IntegerField(required=False)

    class Meta:
        model = Task
        fields = ["text", "date", "user_id", "session_key"]
    

tasks/views.py
from django.http import JsonResponse
from django.views import View

from tasks.models import Task
from tasks.mixins import TaskMixin
# Create your views here.

class TaskDeleteView(TaskMixin, View):
    def post(self, request, *args, **kwargs):
        task = Task.objects.get(id=request.POST.get('task_id'))

        task.delete()

        response_data = {
            "task_items_html": self.render_tasks(request),
        }

        return JsonResponse(response_data)


class TaskUpdateView(TaskMixin, View):
    def post(self, request, *args, **kwargs):
        task = Task.objects.get(id=request.POST.get('task_id'))

        task.is_done = (request.POST.get('is_done') != 'True')
        task.save()

        # if not request.GET.get('q'):
        #     request.GET.get('q') = request.POST.get('q') if request.POST.get('q') else None

        response_data = {
            "task_items_html": self.render_tasks(request),
        }

        # if not request.POST.get('q'):
        #     # return redirect(request.META.get('HTTP_REFERER'))
        #     return HttpResponseRedirect(request.META.get('HTTP_REFERER','redirect_if_referer_not_found'))
        
        return JsonResponse(response_data)

tasks/templates/tasks/includes/tasks_template.html
{% comment %} {% user_tasks request as tasks %} {% endcomment %}
{% if tasks.exists %}
{% for task in tasks %}
    <div class="todo-list-item">
        <div class="task-text">
            <p class="{% if task.is_done %}text-decoration-line-through{% endif %}">
                {% comment %} {% if task.headline %} {% endcomment %}
                    {% comment %} {{ task.headline }} {% endcomment %}
                {% comment %} {% else %} {% endcomment %}
                    {{ task.text }}    
                {% comment %} {% endif %} {% endcomment %}
            </p>
            <p class="task-date">
                {% comment %} {% if task.bodyline %}
                    {{ task.bodyline }}
                {% else %} {% endcomment %}
                    {{ task.date }}    
                {% comment %} {% endif %} {% endcomment %}
            </p>
        </div>
        <div class="task-buttons">
            <a class="task-is-done-update" href="{% url "tasks:update_task" %}" 
            data-task-is-done="{{ task.is_done }}" data-task-id="{{ task.id }}" data-q={{ request.GET.q }}>{% csrf_token %}
                <label class="checkbox task-button" for="{{ task.id }}">
                    <input type="checkbox" name="color" {% if task.is_done %}checked{% endif %} id="{{ task.id }}">
                    <span class="checkmark"></span>
                </label>
            </a>
            <a href="{% url "tasks:delete_task" %}" class="button task-button remove-task"
            data-task-id="{{ task.id }}" data-q={% if request.POST.q %}{{ request.POST.q }}{% else %}{{ request.GET.q }}{% endif %}>{% csrf_token %}Удалить</a>
            {% comment %} <input type="hidden" name="{{ task.id }}"> {% endcomment %}
            <input type="hidden" name="{{ request.GET.q }}">
        </div>
    </div>
{% endfor %}
{% else %}
<p>Упс, у вас не задач</p>
{% endif %}