app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('user/', include('users.urls', namespace='users')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.MainView.as_view(), name='index'),
    path('search/', views.MainView.as_view(), name='search'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class TaskUser(AbstractUser):
    image = models.ImageField(upload_to='users', blank=True, null=True, verbose_name="Аватар")
    

    class Meta:
        db_table = 'user'
        verbose_name = "пользователя"
        verbose_name_plural = "Пользователи"
        ordering = ("id", )
    

    def __str__(self) -> str:
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import TaskUser

class UserLoginForm(AuthenticationForm):

    class Meta:
        model = TaskUser
        fields = ["username", "password"]

    username = forms.CharField()
    password = forms.CharField()


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = TaskUser
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

    
    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(forms.ModelForm):

    class Meta:
        model = TaskUser
        fields = ["username", "first_name", "last_name", "email", "image"]
    
    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    image = forms.ImageField(required=False)

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from tasks.models import Task
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm

# Create your views here.

class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form = UserLoginForm
    success_url = reverse_lazy('main:index')

    def get_success_url(self, request) -> str:
        redirect_url = request.POST.get('next', None)
        if redirect_url and redirect_url != reverse('users:logout'):
            return request.POST.get('next')
        return reverse_lazy('main:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вход'
        return context
    
    def form_valid(self, form):
        session_key = self.request.session.session_key  
        user = form.get_user()
        
        if user:
            auth.login(self.request, user)

            if session_key:
                Task.objects.filter(session_key=session_key).update(user=user)

            return HttpResponseRedirect(self.get_success_url(self.request))

class UserRegistrationView(CreateView): #CreateView TemplateView
    template_name = "users/registration.html"
    form_class = UserRegistrationForm
    success_url = reverse_lazy("main:index")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Регистрация"
        return context
    
    def form_valid(self, form):
        form.save()
        session_key = self.request.session.session_key  
        user = form.instance
        
        if user:
            auth.login(self.request, user)

            if session_key:
                Task.objects.filter(session_key=session_key).update(user=user)

            return HttpResponseRedirect(self.success_url)
    

class UserProfileView(LoginRequiredMixin, UpdateView):
    template_name = "users/profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Профиль"
        return context
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse("main:index"))

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<header>
    <div class="header">
        <div class="indent"></div>
        <a class="button" href="{% url "main:index" %}">Главная</a>
    </div>
</header>
{% endblock %}

{% block main %}
<main class="log-main">
    <h1>Войти</h1>
    <form class="login-form" method="post" action="{% url "users:login" %}">
        {% csrf_token %}
        <div class="login-item-container">
            <input class="form-input" type="text" placeholder="Логин" name="username"
                value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required />
            {% if form.username.errors %}
            <p>{{ form.username.errors }}</p>
            {% endif %}
        </div>
        <div class="login-item-container">
            <input class="form-input" type="password" placeholder="Пароль" name="password"
                value="{% if form.password.value %}{{ form.password.value }}{% endif %}" required />
            {% if form.password.errors %}
            <p>{{ form.password.errors }}</p>
            {% endif %}
        </div>
        <div>
            <a class="login-link" href="404.html">Забыли пароль?</a>
            <a class="login-link" href="{% url "users:registration" %}">Создать аккаунт</a>
        </div>

        {% if form.non_field_errors %}
        <p>{{ form.non_field_errors }}</p>
        {% endif %}

        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <button class="button log-button-submit" type="submit">Войти</button>
    </form>
</main>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<header>
    <div class="header">
        <div class="indent"></div>
        {% if user.image %}
        <img class="profile-avatar" src="{{ user.image.url }}" alt="avatar" />
        {% else %}
        <img class="profile-avatar" src="{% static "images/avatar.png" %}" alt="avatar" />
        {% endif %}
        <a class="button" href="{% url "main:index" %}">Главная</a>
    </div>
</header>
{% endblock %}

{% block main %}
<main>
    <div class="profile">
        <h2>Изменить профиль</h2>
        <form class="profile-form" action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="reg-cointainer">
                <div class="form-item-container">
                    <input class="form-input" type="text" placeholder="Введите ваш логин" name="username"
                        value="{{ user.username }}" required />
                    {% if form.username.errors %}
                    <p>{{ form.username.errors }}</p>
                    {% endif %}
                </div>
                <div class="form-item-container">
                    <input class="form-input" type="text" placeholder="Введите ваше имя" name="first_name"
                        value="{{ user.first_name }}" required />
                    {% if form.first_name.errors %}
                    <p>{{ form.first_name.errors }}</p>
                    {% endif %}
                </div>
            </div>
            <div class="reg-cointainer">
                <div class="form-item-container">
                    <input class="form-input" type="text" placeholder="Введите вашу фамилию" name="last_name"
                        value="{{ user.last_name }}" required />
                    {% if form.last_name.errors %}
                    <p>{{ form.last_name.errors }}</p>
                    {% endif %}
                </div>
                <div class="form-item-container">
                    <input class="form-input" type="text" placeholder="Введите ваш email" name="email"
                        value="{{ user.email }}" required />
                    {% if form.email.errors %}
                    <p>{{ form.email.errors }}</p>
                    {% endif %}
                </div>
            </div>
            {% comment %} <div class="reg-cointainer">
                <input class="form-input" type="password" placeholder="Введите старый пароль" />
                <input class="form-input" type="password" placeholder="Введите новый пароль" />
                <input class="form-input" type="password" placeholder="Повторите новый пароль" />
            </div> {% endcomment %}
            <label>
                Изменить аватарку -
                <input type="file" name="image" accept="image/*" />
            </label>
            {% if form.image.errors %}
            <p>{{ form.image.errors }}</p>
            {% endif %}
            <div class="profile-form-buttons-container">
                <button class="button log-button-submit" type="submit">Сохранить</button>
                <a class="button" href="{% url "users:logout" %}">Выход</a>
            </div>
        </form>
    </div>
</main>
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block header %}
<header>
    <div class="header">
        <div class="indent"></div>
        <a class="button" href="{% url "main:index" %}">Главная</a>
    </div>
</header>
{% endblock %}

{% block main %}
<main class="log-main">
    <h1>Регистрация</h1>
    <form class="reg-form" action={% url "users:registration" %} method="post">{% csrf_token %}
        <div class="reg-cointainer">
            <div class="form-item-container">
                <input class="form-input" type="text" name="username" placeholder="Введите ваш логин"
                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required/>
                {% if form.username.errors %}
                <p>{{ form.username.errors }}</p>
                {% endif %}
            </div>
            <div class="form-item-container">
                <input class="form-input" type="text" name="first_name" placeholder="Введите ваше имя"
                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" required/>
                {% if form.first_name.errors %}
                <p>{{ form.first_name.errors }}</p>
                {% endif %}
            </div>
        </div>
        <div class="reg-cointainer">
            <div class="form-item-container">
                <input class="form-input" type="text" name="last_name" placeholder="Введите вашу фамилию"
                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" required/>
                {% if form.last_name.errors %}
                <p>{{ form.last_name.errors }}</p>
                {% endif %}
            </div>
            <div class="form-item-container">
                <input class="form-input" type="text" name="email" placeholder="Введите ваш email"
                    value="{% if form.email.value %}{{ form.email.value }}{% endif %}" required/>
                {% if form.email.errors %}
                <p>{{ form.email.errors }}</p>
                {% endif %}
            </div>
        </div>
        <div class="reg-cointainer">
            <div class="form-item-container">
                <input class="form-input" type="password" name="password1" placeholder="Введите пароль"
                    value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}" required/>
                    {% if form.password2.errors %}
                    <p>{{ form.password2.errors }}</p>
                    {% endif %}
            </div>
            <div class="form-item-container">
                <input class="form-input" type="password" name="password2" placeholder="Повторите пароль"
                    value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}" required/>
            </div>
        </div>
        {% if form.non_field_errors %}
        <p>{{ form.non_field_errors }}</p>
        {% endif %}
        <button class="button log-button-submit" type="submit">
            Создать аккаунт
        </button>
    </form>
</main>
{% endblock %}