app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('user/', include('users.urls', namespace='users')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.MainView.as_view(), name='index'),
    path('search/', views.MainView.as_view(), name='search'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.logout, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
# from django.shortcuts import render
from datetime import datetime
from django.views.generic.base import TemplateView
# Create your views here.

from main.utils import q_search
from tasks.utils import get_user_tasks
from tasks.forms import TaskCreateForm

class MainView(TemplateView):
    template_name = "main/index.html"

    def get(self, request, *args, **kwargs):
        if request.GET.get("q"):
            context = self.get_context_data(**kwargs)
            q_search_result = q_search(request.GET.get("q"))
            
            context["tasks"] = q_search_result.filter(user_id=request.user.id)
            return self.render_to_response(context)

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "title": "Главная",
            "tasks": get_user_tasks(self.request),
            "current_date": datetime.now().strftime("%d.%m.%Y"),
        })
        return context
    
    def post(self, request, *args, **kwargs):
        form = TaskCreateForm(data=request.POST)
        context = self.get_context_data(**kwargs)

        if request.user.is_authenticated:
            form.instance.user_id = request.user.id
        else:
            if request.session.session_key:
                form.instance.session_key = request.session.session_key

        if form.is_valid():
            # Если задача уже существует то пропускаем, если нет то сохраняем
            if get_user_tasks(request).filter(text=form.cleaned_data["text"], date=form.cleaned_data["date"]).exists():
                pass
            else:
                form.save()
        else:
            context["form"] = form

        return self.render_to_response(context)

main/templates/main/index.html
{% extends "base.html" %}

{% load static %}

{% block header %}
<header>
  <div class="header">
    <div class="indent"></div>
    <h1 class="header-title">Список дел</h1>
    <div class="nav-div">
        {% if user.is_authenticated %}
        <div class="main-profile">
            {% if user.image %}
                <img
                    class="profile-avatar"
                    src="{{ user.image.url }}"
                    alt="avatar"/>
                {% else %}
                <img
                    class="profile-avatar"
                    src="{% static "images/avatar.png" %}"
                    alt="avatar"/>
                {% endif %}
                <!-- Выпадающее меню -->
                <div class="profile-menu">
                <div class="menu-container">
                    <h2>Профиль</h2>
                    <div class="profile-content">
                        <p>Логин - 
                            {% if user.username %}
                                {{ user.username }}
                            {% else %}
                                Не нашли ваше логин в базе данных
                            {% endif %}
                        </p>
                        <p>Имя - 
                            {% if user.first_name %}
                                {{ user.first_name }}
                            {% else %}
                                Не нашли ваше имя в базе данных
                            {% endif %}
                        </p>
                        <p>Фамилия - 
                            {% if user.last_name %}
                                {{ user.last_name }}
                            {% else %}
                                Не нашли вашу фамилию в базе данных
                            {% endif %}
                        </p>
                        <p>Email - 
                            {% if user.email %}
                                {{ user.email }}
                            {% else %}
                                Не нашли ваш email в базе данных
                            {% endif %}
                        </p>
                        <a class="button" href="{% url "users:profile" %}">Изменить</a>
                    </div>
                    <div class="profile-contol-buttons">
                    {% if user.is_staff %}
                    <a class="button" href="{% url "admin:index" %}">Админ панель</a>
                    {% endif %}
                    <a class="button" href="{% url "users:logout" %}">Выход</a>
                    </div>
                </div>
        {% else %}
            <a class="nav-link" href="{% url "users:login" %}">Войти</a>
        {% endif %}
    </div>
        <!-- Конец выпадающего меню -->
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block main %}
    <main>
    <div class="main">

        <form class="tasks-search" action="{% url "main:search" %}" method="get" >
            <input class="search-input" type="search" name="q" placeholder="Поиск" id="search-input">
            <button class="button search-button"><img class="search-image" src="{% static "images/search.png" %}" alt="search"></button>
        </form>

        <div class="task-main">
            <div class="todo-list" id="todo-list-id">
                <!-- Разметка задач -->
                {% include "tasks/includes/tasks_template.html" %}
                <input type="hidden" name="q" value={{ request.GET.q.value }} id="q-id">
                <!-- Конец разметки задач -->
            </div>

            <form class="add-task" method='post' action={% url "main:index" %}>
                {% csrf_token %}
                <div class="add-task-inputs">
                    <textarea class="task-text add-task-text-input" type="text" placeholder="Текст задачи" name="text" required>{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
                    {% if form.text.errors %}
                        <p>{{ form.text.errors }}</p>
                    {% endif %}
                    <input class="task-date add-task-date-input" type="date" placeholder="Дата задачи {dd:mm:yy}" name="date" value="{% if form.date.value %}{{ form.date.value }}{% endif %}" required>
                    <input type="hidden" name="session_key" value="{{ request.session.session_key }}">
                    {% if form.date.errors %}
                        <p>{{ form.date.errors }}</p>
                    {% endif %}
                </div>
                <button type="submit" class="button">Добавить задачу</button>
            </form>
        </div>
    </div>
    </main>
{% endblock %}